server {
    listen 80;
    server_name _;
    # บังคับเข้า HTTP ให้เด้งไป HTTPS อัตโนมัติ
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    # ชี้เป้าไปที่ไฟล์ SSL ที่เราเตรียมไว้
    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/bde.go.th.key;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
