server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # ป้องกันอาการ Refresh แล้วขึ้น 404 Not Found
        try_files $uri $uri/ /index.html;
    }
}