server {
    listen 80;
    server_name _;
    
    root /usr/share/nginx/html;
    index index.html index.htm;

    # คำสั่งนี้คือหัวใจสำคัญที่แก้เว็บขึ้น 404
    location / {
        try_files $uri $uri/ /index.html; 
    }
}